
import streamlit as st
import pandas as pd

from database import (
    get_supabase_client
)


# ============================================================
# PAGE HEADER
# ============================================================

st.title(
    "🗃️ Audit Logs"
)

st.caption(
    "Persistent Incident & Resource Decision History"
)

st.info(
    "Audit records are loaded from the hosted Supabase "
    "database. Incident/DSS decisions and resource-allocation "
    "decisions remain logically separated for traceability."
)


# ============================================================
# DATABASE CLIENT
# ============================================================

try:

    client = get_supabase_client()

except Exception as exc:

    st.error(
        "The hosted audit database could not be reached."
    )

    st.exception(
        exc
    )

    st.stop()


# ============================================================
# SAFE TABLE LOADER
# ============================================================

def load_supabase_table(
    table_name,
    order_column=None
):
    """
    Load a complete Supabase table into a DataFrame.
    """

    try:

        query = (
            client
            .table(table_name)
            .select("*")
        )

        if order_column:

            query = query.order(
                order_column,
                desc=True
            )

        response = query.execute()

        records = response.data or []

        return pd.DataFrame(
            records
        )

    except Exception as exc:

        st.error(
            f"Unable to load hosted table: {table_name}"
        )

        st.exception(
            exc
        )

        return pd.DataFrame()


# ============================================================
# LOAD HOSTED AUDIT TABLES
# ============================================================

dss_audit_df = load_supabase_table(
    "dss_incident_audit",
    "decision_timestamp"
)

resource_audit_df = load_supabase_table(
    "resource_allocation_audit",
    "decision_timestamp"
)


# ============================================================
# SUMMARY
# ============================================================

st.subheader(
    "01 · Audit Summary"
)

col1, col2, col3, col4 = st.columns(4)


with col1:

    st.metric(
        "Incident Decisions",
        len(dss_audit_df)
    )


with col2:

    st.metric(
        "Resource Decisions",
        len(resource_audit_df)
    )


with col3:

    confirmed_count = 0

    if (
        not resource_audit_df.empty
        and "operator_action"
        in resource_audit_df.columns
    ):

        confirmed_count = (
            resource_audit_df[
                "operator_action"
            ]
            .eq("CONFIRMED")
            .sum()
        )

    st.metric(
        "Confirmed",
        int(confirmed_count)
    )


with col4:

    override_count = 0

    if (
        not resource_audit_df.empty
        and "operator_action"
        in resource_audit_df.columns
    ):

        override_count = (
            resource_audit_df[
                "operator_action"
            ]
            .eq("OVERRIDDEN")
            .sum()
        )

    st.metric(
        "Overrides",
        int(override_count)
    )


st.divider()


# ============================================================
# AUDIT TABS
# ============================================================

incident_tab, resource_tab = st.tabs(
    [
        "INCIDENT / DSS AUDIT",
        "RESOURCE ALLOCATION AUDIT"
    ]
)


# ============================================================
# INCIDENT / DSS AUDIT
# ============================================================

with incident_tab:

    st.subheader(
        "02 · Incident Decision Audit"
    )

    st.caption(
        "Persistent hosted history generated by the "
        "ML + DSS incident-analysis workflow."
    )


    if dss_audit_df.empty:

        st.info(
            "No hosted DSS incident audit records "
            "are currently available."
        )

    else:

        search_text = st.text_input(
            "Search Incident Audit",
            placeholder=(
                "Search decision ID, incident type, "
                "priority, response pathway..."
            ),
            key="hosted_incident_audit_search"
        )


        filtered_dss = (
            dss_audit_df.copy()
        )


        if search_text.strip():

            search_mask = (
                filtered_dss
                .astype(str)
                .apply(
                    lambda column:
                    column.str.contains(
                        search_text,
                        case=False,
                        na=False
                    )
                )
                .any(axis=1)
            )

            filtered_dss = (
                filtered_dss[
                    search_mask
                ]
            )


        st.write(
            f"Showing **{len(filtered_dss)}** "
            "incident decision record(s)."
        )


        preferred_dss_columns = [
            "decision_timestamp",
            "decision_id",
            "primary_type",
            "location_description",
            "provost_incident_category",
            "incident_subcategory",
            "priority",
            "arrest_probability_percent",
            "arrest_prediction",
            "recommended_response_type",
            "operator_uid"
        ]


        available_dss_columns = [
            column
            for column in preferred_dss_columns
            if column in filtered_dss.columns
        ]


        st.dataframe(
            filtered_dss[
                available_dss_columns
            ]
            if available_dss_columns
            else filtered_dss,
            use_container_width=True,
            hide_index=True
        )


        if (
            not filtered_dss.empty
            and "decision_id"
            in filtered_dss.columns
        ):

            st.markdown(
                "### Incident Record Inspector"
            )

            selected_incident = (
                st.selectbox(
                    "Select Incident Decision",
                    options=filtered_dss[
                        "decision_id"
                    ].astype(str).tolist(),
                    key="hosted_incident_record_selector"
                )
            )


            selected_row = (
                filtered_dss[
                    filtered_dss[
                        "decision_id"
                    ].astype(str)
                    == str(
                        selected_incident
                    )
                ]
                .iloc[0]
            )


            with st.container(
                border=True
            ):

                for key, value in (
                    selected_row
                    .to_dict()
                    .items()
                ):

                    st.write(
                        f"**{key}:** {value}"
                    )


# ============================================================
# RESOURCE ALLOCATION AUDIT
# ============================================================

with resource_tab:

    st.subheader(
        "03 · Resource Allocation Audit"
    )

    st.caption(
        "Persistent hosted history of team recommendations, "
        "operator confirmation/override actions, and final "
        "selected resources."
    )


    if resource_audit_df.empty:

        st.info(
            "No hosted resource-allocation records "
            "are currently available."
        )

    else:

        filter_col1, filter_col2 = (
            st.columns(2)
        )


        with filter_col1:

            action_options = [
                "ALL"
            ]

            if (
                "operator_action"
                in resource_audit_df.columns
            ):

                action_options += sorted(
                    resource_audit_df[
                        "operator_action"
                    ]
                    .dropna()
                    .astype(str)
                    .unique()
                    .tolist()
                )


            selected_action = st.selectbox(
                "Operator Action",
                options=action_options,
                key="hosted_resource_action_filter"
            )


        with filter_col2:

            operator_options = [
                "ALL"
            ]

            if (
                "operator_uid"
                in resource_audit_df.columns
            ):

                operator_options += sorted(
                    resource_audit_df[
                        "operator_uid"
                    ]
                    .dropna()
                    .astype(str)
                    .unique()
                    .tolist()
                )


            selected_operator = st.selectbox(
                "Operator UID",
                options=operator_options,
                key="hosted_resource_operator_filter"
            )


        filtered_resource = (
            resource_audit_df.copy()
        )


        if (
            selected_action != "ALL"
            and "operator_action"
            in filtered_resource.columns
        ):

            filtered_resource = (
                filtered_resource[
                    filtered_resource[
                        "operator_action"
                    ].astype(str)
                    == selected_action
                ]
            )


        if (
            selected_operator != "ALL"
            and "operator_uid"
            in filtered_resource.columns
        ):

            filtered_resource = (
                filtered_resource[
                    filtered_resource[
                        "operator_uid"
                    ].astype(str)
                    == selected_operator
                ]
            )


        st.write(
            f"Showing **{len(filtered_resource)}** "
            "resource decision record(s)."
        )


        preferred_resource_columns = [
            "decision_timestamp",
            "decision_id",
            "incident_id",
            "operator_uid",
            "operational_response",
            "incident_zone",
            "required_capability",
            "recommended_team_id",
            "recommended_team_score",
            "operator_action",
            "selected_team_id",
            "selected_team_score",
            "override_reason"
        ]


        available_resource_columns = [
            column
            for column in preferred_resource_columns
            if column in filtered_resource.columns
        ]


        st.dataframe(
            filtered_resource[
                available_resource_columns
            ]
            if available_resource_columns
            else filtered_resource,
            use_container_width=True,
            hide_index=True
        )


        if (
            not filtered_resource.empty
            and "decision_id"
            in filtered_resource.columns
        ):

            st.markdown(
                "### Resource Decision Inspector"
            )


            selected_resource_decision = (
                st.selectbox(
                    "Select Resource Decision",
                    options=filtered_resource[
                        "decision_id"
                    ].astype(str).tolist(),
                    key="hosted_resource_record_selector"
                )
            )


            selected_resource_row = (
                filtered_resource[
                    filtered_resource[
                        "decision_id"
                    ].astype(str)
                    == str(
                        selected_resource_decision
                    )
                ]
                .iloc[0]
            )


            with st.container(
                border=True
            ):

                c1, c2, c3 = (
                    st.columns(3)
                )


                with c1:

                    st.caption(
                        "RECOMMENDED TEAM"
                    )

                    st.markdown(
                        "### "
                        + str(
                            selected_resource_row.get(
                                "recommended_team_id",
                                "N/A"
                            )
                        )
                    )


                with c2:

                    st.caption(
                        "FINAL SELECTED TEAM"
                    )

                    st.markdown(
                        "### "
                        + str(
                            selected_resource_row.get(
                                "selected_team_id",
                                "N/A"
                            )
                        )
                    )


                with c3:

                    st.caption(
                        "OPERATOR ACTION"
                    )

                    st.markdown(
                        "### "
                        + str(
                            selected_resource_row.get(
                                "operator_action",
                                "N/A"
                            )
                        )
                    )


                st.write(
                    "**Operator UID:**",
                    selected_resource_row.get(
                        "operator_uid",
                        "N/A"
                    )
                )

                st.write(
                    "**Operational Response:**",
                    selected_resource_row.get(
                        "operational_response",
                        "N/A"
                    )
                )

                st.write(
                    "**Incident Zone:**",
                    selected_resource_row.get(
                        "incident_zone",
                        "N/A"
                    )
                )

                st.write(
                    "**Required Capability:**",
                    selected_resource_row.get(
                        "required_capability",
                        "N/A"
                    )
                )


                override_reason = (
                    selected_resource_row.get(
                        "override_reason",
                        None
                    )
                )


                if (
                    pd.notna(
                        override_reason
                    )
                    and str(
                        override_reason
                    ).strip()
                    not in [
                        "",
                        "None",
                        "nan"
                    ]
                ):

                    st.info(
                        "Override Reason: "
                        + str(
                            override_reason
                        )
                    )


# ============================================================
# AUDIT NOTE
# ============================================================

st.divider()

st.caption(
    "Hosted Audit Architecture: incident analysis and "
    "resource-allocation records are stored persistently "
    "in separate Supabase tables."
)

st.warning(
    "All response-team and zone information is simulated. "
    "This academic prototype contains no real military "
    "deployment records."
)
